codecoins/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
]

game/urls.py
from django.urls import path

from . import views

app_name = 'game'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('task/<int:task_id>/', views.detail, name='detail'),
  path('task/<int:task_id>/subtasks/', views.subtasks, name='subtasks'),
  path('task/<int:task_id>/join/', views.join, name='join'),
]

game/models.py
import datetime

from django.db import models
from django.utils import timezone

class Task(models.Model):
    task_description = models.CharField(max_length=200)
    code_coins = models.IntegerField(default=0, null=True, blank=True)
    assign_date = models.DateTimeField('assignment date', null=True, blank=True)
    finish_date = models.DateTimeField('finish date', null=True, blank=True)
    def __str__(self):
      return self.task_description
    def was_assign_recently(self):
      return self.assign_date >= timezone.now() - datetime.timedelta(days=1)

class SubTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    sub_task_description = models.CharField(max_length=200)
    def __str__(self):
      return self.sub_task_description

game/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Task, SubTask

class IndexView(generic.ListView):
    template = 'game/index.html'
    context_object_name = 'latest_task_list'

    def get_queryset(self):
        return Task.objects.order_by('-assign_date')[:5]

def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, 'game/detail.html', {'task': task})

def subtasks(request, task_id):
  response = "You're looking at the subtask of task %s."
  return HttpResponse(response % task_id)

def join(request, task_id):
  return HttpResponse("You're ask for the task %s." % task_id)

game/templates/game/detail.html
<h1>{{task.task_description }} <h1>
<ul>
{% for subtask in task.subtask_set.all %}
    <li>{{ subtask.subtaks_description }}</li>
{% endfor %}
</ul>

game/templates/game/index.html
{% if latest_task_list %}
    <ul>
    {% for task in latest_task_list %}
        <li><a href="{% url 'game:detail' task.id %}">{{ task.task_description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Tasks are available.</p>
{% endif %}

game/templates/game/task_list.html
<h1>Lista de tareas </h1>
{% if latest_task_list %}
    <ul>
    {% for task in latest_task_list %}
        <li><a href="{% url 'game:detail' task.id %}">{{ task.task_description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Tasks are available.</p>
{% endif %}